[server]
  name = "todo"
  addr = ":8080"

[server.logger]
  level = "debug"

# 数据库相关
[database]
  driver = "mysql"

[mysql]
  dbHost = "39.96.196.123"
  dbPort = "3306"
  dbName = "todo"
  dbParams = "parseTime=true&loc=Local"
  dbUser = "root"
  dbPasswd = "5211314@Yuan"


